/**
 * Build playground/og/index.html from package.json, then screenshot to
 * playground/public/og.png. Does not boot @arrow-js/sandbox.
 *
 * Run from playground/:  pnpm og:generate
 * Or from repo root:     pnpm og:generate
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const playground = join(here, '..')
const root = join(playground, '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const meta = pkg.comark ?? {}

const name = pkg.name
const headline = meta.headline ?? name
const tagline = meta.tagline ?? pkg.description
const install = meta.install ?? `npm i ${name}`

const inputCard = `
<pre><span class="t">\`\`\`</span><span class="k">arrow</span>
<span class="v">const</span> <span class="t">state = reactive({ count: 0 })</span>

<span class="v">export default</span> <span class="t">html\`</span>
  <span class="t">&lt;button @click="\${() =&gt; state.count++}"&gt;</span>
    <span class="t">Clicked \${() =&gt; state.count}</span>
  <span class="t">&lt;/button&gt;</span>
<span class="t">\`</span>
<span class="t">\`\`\`</span></pre>`

const outputCard = `
<div class="out result">
  <button class="widget" type="button">Clicked 3</button>
  <div class="caption">QuickJS · WASM sandbox</div>
</div>`

const html = `<!doctype html>
<!--
  Generated by playground/og/generate.mjs — do not edit by hand.
  Source of playground/public/og.png (1200×630).
  Used as the site Open Graph image and the README cover.
  Regenerate: pnpm og:generate
-->
<html lang="en">
<head>
<meta charset="utf-8" />
<style>
  :root {
    --gold: #b59a00;
    --gold-fill: #f0db4f;
    --fg: #111;
    --muted: #666;
    --border: #ddd;
  }
  * { box-sizing: border-box; margin: 0; }
  html, body { width: 1200px; height: 630px; overflow: hidden; }
  body {
    font-family: Inter, 'Segoe UI', 'Liberation Sans', Arial, sans-serif;
    color: var(--fg);
    background: #fff;
    background-image:
      linear-gradient(#0000 0, #0000 0),
      radial-gradient(circle at 1px 1px, #e5e5e5 1px, transparent 0);
    background-size: 100% 100%, 28px 28px;
    display: grid;
    grid-template-columns: 520px 1fr;
    gap: 40px;
    padding: 56px 72px 48px;
  }
  .left { display: flex; flex-direction: column; justify-content: center; }
  .brand { display: flex; align-items: center; gap: 14px; font-size: 22px; color: var(--muted); }
  .brand .dot {
    width: 12px; height: 12px; border-radius: 50%;
    background: var(--gold-fill); border: 1px solid var(--fg);
  }
  h1 { font-size: 58px; line-height: 1.05; letter-spacing: -0.03em; font-weight: 700; margin-top: 28px; }
  h1 .comark { color: var(--gold); }
  p.lede { margin-top: 22px; font-size: 24px; line-height: 1.35; color: #444; max-width: 480px; }
  .install {
    display: inline-flex; align-items: center; gap: 12px; align-self: flex-start; margin-top: 34px;
    font-family: 'DejaVu Sans Mono', 'Liberation Mono', monospace; font-size: 20px;
    padding: 12px 18px; border: 1.5px solid var(--border); border-radius: 10px; background: #fff;
  }
  .install .p { color: #999; }
  .right { display: flex; flex-direction: column; gap: 14px; justify-content: center; }
  .card {
    border: 1.5px solid var(--border); border-radius: 14px; background: #fff; overflow: hidden;
    box-shadow: 0 8px 30px rgba(0,0,0,.06);
  }
  .card .bar {
    display: flex; align-items: center; gap: 8px; padding: 10px 16px;
    border-bottom: 1px solid #eee; font-size: 14px; color: #888;
    letter-spacing: .06em; text-transform: uppercase;
  }
  .card .bar b { color: var(--gold); font-weight: 600; }
  pre {
    font-family: 'DejaVu Sans Mono', 'Liberation Mono', monospace;
    font-size: 15px; line-height: 1.45; padding: 16px 20px; white-space: pre;
  }
  .k { color: #b35c00; } .v { color: #0a66c2; } .t { color: #333; }
  .arrow { align-self: center; color: var(--gold); font-size: 26px; line-height: 1; margin: -4px 0; }
  .result { padding: 28px 24px; display: flex; flex-direction: column; align-items: center; gap: 14px; }
  .widget {
    font: inherit; font-size: 22px; padding: 12px 22px; border-radius: 10px;
    border: 1.5px solid var(--fg); background: var(--gold-fill); cursor: default;
  }
  .caption {
    font-size: 13px; color: var(--muted);
    font-family: 'DejaVu Sans Mono', 'Liberation Mono', monospace;
  }
</style>
</head>
<body>
  <div class="left">
    <div>
      <div class="brand"><span class="dot"></span> ${name}</div>
      <h1>${headline}<br />for <span class="comark">Comark</span></h1>
      <p class="lede">${tagline}</p>
      <div class="install"><span class="p">$</span> ${install}</div>
    </div>
  </div>
  <div class="right">
    <div class="card">
      <div class="bar"><b>markdown</b> · fence</div>
      ${inputCard}
    </div>
    <div class="arrow">▼</div>
    <div class="card">
      <div class="bar"><b>comark</b> · sandbox</div>
      ${outputCard}
    </div>
  </div>
</body>
</html>
`

writeFileSync(join(here, 'index.html'), html)
execFileSync(
  'npx',
  ['playwright', 'screenshot', '--viewport-size=1200,630', 'og/index.html', 'public/og.png'],
  { cwd: playground, stdio: 'inherit' },
)
console.log(`Wrote ${join(here, 'index.html')}`)
console.log(`Wrote ${join(playground, 'public/og.png')}`)
