/**
 * The Comark theme: completion menu, docs panel and syntax colors. Every
 * color is a CSS variable with light and dark values, so hosts restyle with
 * CSS only. It is a base theme: host themes win.
 */
import { EditorView } from '@codemirror/view'

const light = {
  '--cme-menu-bg': '#ffffff',
  '--cme-menu-fg': '#1f2328',
  '--cme-menu-muted': '#6e7781',
  '--cme-menu-border': 'rgba(31, 35, 40, 0.12)',
  '--cme-menu-shadow': '0 12px 32px -8px rgba(31, 35, 40, 0.22), 0 2px 6px rgba(31, 35, 40, 0.08)',
  '--cme-menu-selected': 'rgba(9, 105, 218, 0.1)',
  '--cme-menu-header': '#f6f8fa',
  '--cme-accent': '#0969da',
  '--cme-code-bg': 'rgba(175, 184, 193, 0.2)',
  '--cme-mark': '#8c959f',
  '--cme-component': '#8250df',
  '--cme-attr': '#0550ae',
  '--cme-value': '#0a3069',
  '--cme-class': '#953800',
  '--cme-binding': '#cf222e',
  '--cme-meta': '#6639ba',
  '--cme-math': '#116329',
  '--cme-slot': '#bf3989',
}

const dark = {
  '--cme-menu-bg': '#1c2128',
  '--cme-menu-fg': '#e6edf3',
  '--cme-menu-muted': '#8b949e',
  '--cme-menu-border': 'rgba(240, 246, 252, 0.12)',
  '--cme-menu-shadow': '0 12px 32px -8px rgba(0, 0, 0, 0.6), 0 2px 6px rgba(0, 0, 0, 0.3)',
  '--cme-menu-selected': 'rgba(56, 139, 253, 0.18)',
  '--cme-menu-header': '#22272e',
  '--cme-accent': '#58a6ff',
  '--cme-code-bg': 'rgba(110, 118, 129, 0.3)',
  '--cme-mark': '#6e7681',
  '--cme-component': '#d2a8ff',
  '--cme-attr': '#79c0ff',
  '--cme-value': '#a5d6ff',
  '--cme-class': '#ffa657',
  '--cme-binding': '#ff7b72',
  '--cme-meta': '#d2a8ff',
  '--cme-math': '#7ee787',
  '--cme-slot': '#f778ba',
}

/** Icon letter and color per item `type`. */
const ICONS: Record<string, [string, string]> = {
  'component': ['◆', '#8250df'],
  'inline-component': ['◇', '#8250df'],
  'prop': ['P', '#0969da'],
  'prop-bound': [':', '#cf222e'],
  'slot': ['#', '#bf3989'],
  'value': ['=', '#1a7f37'],
  'binding-root': ['$', '#cf222e'],
  'binding-key': ['{', '#cf222e'],
  'binding-leaf': ['•', '#cf222e'],
  'class': ['.', '#953800'],
  'id': ['#', '#953800'],
  'alert': ['!', '#9a6700'],
  'fence': ['`', '#57606a'],
  'language': ['λ', '#57606a'],
  'snippet': ['✦', '#6e7781'],
  'heading': ['H', '#57606a'],
  'list': ['•', '#57606a'],
  'quote': ['❝', '#57606a'],
  'table': ['⊞', '#57606a'],
  'divider': ['—', '#57606a'],
  'mark': ['B', '#57606a'],
  'link': ['↗', '#0969da'],
  'image': ['▣', '#0969da'],
  'footnote': ['¹', '#0969da'],
  'html': ['<', '#e16f24'],
  'math': ['∑', '#116329'],
  'keyword': ['K', '#6e7781'],
  'task': ['☐', '#57606a'],
  'frontmatter': ['—', '#6639ba'],
  'close': ['⏎', '#8250df'],
}

const iconRules = Object.fromEntries(Object.entries(ICONS).flatMap(([type, [glyph, color]]) => [
  [`.cm-tooltip-autocomplete .cm-completionIcon-${type}`, { backgroundColor: `color-mix(in srgb, ${color} 14%, transparent)`, color }],
  [`.cm-tooltip-autocomplete .cm-completionIcon-${type}:after`, { content: JSON.stringify(glyph) }],
]))

export const comarkTheme = EditorView.baseTheme({
  '&light, &light .cm-tooltip': light,
  '&dark, &dark .cm-tooltip': dark,

  // syntax
  '.cm-comark-mark': { color: 'var(--cme-mark)' },
  '.cm-comark-component': { color: 'var(--cme-component)', fontWeight: '600' },
  '.cm-comark-attr': { color: 'var(--cme-attr)' },
  '.cm-comark-value': { color: 'var(--cme-value)' },
  '.cm-comark-class, .cm-comark-id': { color: 'var(--cme-class)' },
  '.cm-comark-binding': { color: 'var(--cme-binding)' },
  '.cm-comark-meta': { color: 'var(--cme-meta)' },
  '.cm-comark-math': { color: 'var(--cme-math)' },
  '.cm-comark-slot': { color: 'var(--cme-slot)', fontWeight: '600' },
  '.cm-comark-alert': { color: 'var(--cme-accent)', fontWeight: '600' },

  // menu
  '.cm-tooltip.cm-tooltip-autocomplete': {
    background: 'var(--cme-menu-bg)',
    color: 'var(--cme-menu-fg)',
    border: '1px solid var(--cme-menu-border)',
    borderRadius: '10px',
    boxShadow: 'var(--cme-menu-shadow)',
    padding: '4px',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul': {
    fontFamily: 'inherit',
    fontSize: '13px',
    maxHeight: '19em',
    minWidth: '240px',
    maxWidth: 'min(520px, 90vw)',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '0 8px',
    minHeight: '28px',
    lineHeight: '28px',
    borderRadius: '6px',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': {
    background: 'var(--cme-menu-selected)',
    color: 'inherit',
  },
  '.cm-tooltip-autocomplete .cm-completionLabel': { fontFamily: 'var(--cme-mono, ui-monospace, SFMono-Regular, Menlo, monospace)' },
  '.cm-tooltip-autocomplete .cm-completionMatchedText': { textDecoration: 'none', color: 'var(--cme-accent)', fontWeight: '600' },
  '.cm-tooltip.cm-tooltip-autocomplete .cm-completionDetail': {
    marginLeft: 'auto',
    paddingLeft: '16px',
    fontStyle: 'normal',
    fontSize: '12px',
    color: 'var(--cme-menu-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '220px',
  },
  '.cm-tooltip-autocomplete .cm-completionIcon': {
    boxSizing: 'border-box',
    width: '20px',
    height: '20px',
    lineHeight: '20px',
    padding: '0',
    borderRadius: '5px',
    textAlign: 'center',
    fontSize: '11px',
    fontWeight: '700',
    opacity: '1',
    flexShrink: '0',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
  },
  ...iconRules,
  '.cm-comark-glyph': { width: '20px', textAlign: 'center', fontSize: '15px', flexShrink: '0' },
  '.cm-comark-swatch': { width: '12px', height: '12px', borderRadius: '3px', border: '1px solid var(--cme-menu-border)', flexShrink: '0' },
  '.cm-comark-chevron': { color: 'var(--cme-menu-muted)', fontSize: '16px', marginLeft: '4px', width: '10px' },
  'li[aria-selected] .cm-comark-chevron': { color: 'var(--cme-accent)' },

  // section headers (breadcrumbs)
  '.cm-comark-section': {
    display: 'list-item',
    listStyle: 'none',
    padding: '6px 8px 4px',
    fontSize: '11px',
    fontWeight: '600',
    letterSpacing: '0.02em',
    color: 'var(--cme-menu-muted)',
    textTransform: 'none',
  },
  '.cm-comark-crumb-sep': { padding: '0 5px', opacity: '0.6' },
  '.cm-comark-crumb-last': { color: 'var(--cme-menu-fg)' },
  '.cm-tooltip-autocomplete ul li.cm-comark-section:not(:first-child)': { borderTop: '1px solid var(--cme-menu-border)', marginTop: '4px' },

  // docs panel
  '.cm-tooltip-hover .cm-comark-info': { padding: '8px 10px', maxWidth: '380px', fontSize: '12.5px', lineHeight: '1.5' },
  '.cm-tooltip.cm-tooltip-hover': {
    background: 'var(--cme-menu-bg)',
    color: 'var(--cme-menu-fg)',
    border: '1px solid var(--cme-menu-border)',
    borderRadius: '10px',
    boxShadow: 'var(--cme-menu-shadow)',
  },
  '.cm-tooltip.cm-completionInfo': {
    background: 'var(--cme-menu-bg)',
    color: 'var(--cme-menu-fg)',
    border: '1px solid var(--cme-menu-border)',
    borderRadius: '10px',
    boxShadow: 'var(--cme-menu-shadow)',
    padding: '10px 12px',
    maxWidth: '380px',
    fontSize: '12.5px',
    lineHeight: '1.5',
  },
  '.cm-comark-info-title': { fontFamily: 'var(--cme-mono, ui-monospace, monospace)', fontWeight: '700', marginBottom: '4px', color: 'var(--cme-component)' },
  '.cm-comark-info-text': { color: 'var(--cme-menu-fg)', marginBottom: '6px' },
  '.cm-comark-info code': { background: 'var(--cme-code-bg)', borderRadius: '4px', padding: '0 4px', fontSize: '0.95em' },
  '.cm-comark-info-value': { display: 'flex', gap: '8px', alignItems: 'baseline', marginBottom: '6px' },
  '.cm-comark-info-label': { color: 'var(--cme-menu-muted)', fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.04em' },
  '.cm-comark-info-rows': { borderCollapse: 'collapse', width: '100%', margin: '4px 0' },
  '.cm-comark-info-rows td': { padding: '2px 8px 2px 0', verticalAlign: 'top', borderTop: '1px solid var(--cme-menu-border)' },
  '.cm-comark-info-name': { fontFamily: 'var(--cme-mono, ui-monospace, monospace)', color: 'var(--cme-attr)', whiteSpace: 'nowrap' },
  '.cm-comark-info-type': { color: 'var(--cme-menu-muted)', fontSize: '11.5px' },
  '.cm-comark-example': {
    margin: '8px 0 2px',
    padding: '8px 10px',
    background: 'var(--cme-code-bg)',
    borderRadius: '6px',
    fontSize: '12px',
    whiteSpace: 'pre-wrap',
    fontFamily: 'var(--cme-mono, ui-monospace, monospace)',
  },
  '.cm-comark-example .tok-heading': { fontWeight: '700' },
  '.cm-comark-example .tok-emphasis': { fontStyle: 'italic' },
  '.cm-comark-example .tok-strong': { fontWeight: '700' },
  '.cm-comark-info-link': { display: 'inline-block', marginTop: '6px', color: 'var(--cme-accent)', textDecoration: 'none' },
})
